### ISSUE TITLE
Plausible Template Deployment Error + Crashing

### ISSUE THREAD

**Issue by KyTechInc** [MykalMachon/railway-plausible#1]
I'm attempting to deploy the Plausible template in railway. I have left all the variables at their default in the template. As the read me says, the Plausible module spins up first before the clickhouse. I then try to edit and save the CLICKHOUSE_DATABASE_URL to force a rebuild. I'm left with the same repeating error until the module crashes.

Below you will find the block of log/errors that continue to repeat until I get the crash notice.

create Plausible.Repo database if it doesn't exist

17:35:39.448 [error] Ch.Connection (#PID<0.170.0>) failed to connect: ** (Mint.TransportError) non-existing domain

17:35:39.448 [error] Ch.Connection (#PID<0.171.0>) failed to connect: ** (Mint.TransportError) non-existing domain

create Plausible.IngestRepo database if it doesn't exist

** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: :nxdomain}}

(plausible 0.0.1) lib/plausible_release.ex:40: anonymous fn/2 in Plausible.Release.createdb/0

(elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3

(plausible 0.0.1) lib/plausible_release.ex:39: Plausible.Release.createdb/0

nofile:1: (file)

(stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7

Loading plausible..

Starting dependencies..

Starting repos..

create Plausible.Repo database if it doesn't exist

17:35:46.385 [error] Ch.Connection (#PID<0.171.0>) failed to connect: ** (Mint.TransportError) non-existing domain

17:35:46.385 [error] Ch.Connection (#PID<0.172.0>) failed to connect: ** (Mint.TransportError) non-existing domain

create Plausible.IngestRepo database if it doesn't exist

** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: :nxdomain}}

(plausible 0.0.1) lib/plausible_release.ex:40: anonymous fn/2 in Plausible.Release.createdb/0

(elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3

(plausible 0.0.1) lib/plausible_release.ex:39: Plausible.Release.createdb/0

nofile:1: (file)

(stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7

**Comment by MykalMachon** [comment]
Hi @KyTechInc, thanks for submitting an issue about this.
Do you mind sending over the following pieces of info so I can try and help your sort this out? 
- a screenshot of your current `CLICKHOUSE_DATABASE_URL` value in the Plausible Analytics service?
  - it should look like this 
  - ![image](https://github.com/MykalMachon/railway-plausible/assets/7844994/5faf8228-61c8-436c-b2d7-34d1a16fdbfb)
- a screenshot of the Private Networking section under settings in your Clickhouse service? 
  - it should look like this
  - ![image](https://github.com/MykalMachon/railway-plausible/assets/7844994/99cd6c90-e85e-4d83-8e4d-95cb101b9982)
 
---
**If both of these sections look identical to the examples above** (specifically, if the CLICKHOUSE_DATABASE_URL variable matches exactly, and the private networking is setup and labeled as `clickhouse`) then I would suggest simply redeploying the Plausible Analytics service one more time. 

You can do this by going into the Plausible Analytics service, going to the deployments tab, clicking the three dots on the crashed deployment, and clicking "redeploy" ([see the railway docs for this here](https://docs.railway.app/deploy/deployments#redeploy)).

I've noticed that sometimes Railway doesn't always redeploy properly after an environment variable change and it needs a manual kick from time to time to properly pickup the new variables.

**Comment by KyTechInc** [comment]
Hey @MykalMachon,

Thanks for the prompt reply! I deleted my deployment after posting so that I wasn't incurring usage billing. (This was also the 3 time I had redeployed fully from scratch to troubleshoot before submitting)

I've spun up a fresh template deploy to test again.

Here are the two requested screenshots:

<img width="849" alt="image" src="https://github.com/MykalMachon/railway-plausible/assets/118579808/3b5bbd77-ff6f-42c8-8b83-2f516a9b1326">

<img width="747" alt="image" src="https://github.com/MykalMachon/railway-plausible/assets/118579808/a948e0e9-e72e-4a5f-b211-15b16b22097c">

I have also tried the manual redeploy method you suggested after ensuring that the clickhouse module is full up and green. No dice there, same looping set of log errors and the Postgres db remains empty with no tables as well.

Please let me know if I can try or gather anything further.

Thanks!

**Comment by MykalMachon** [comment]
@KyTechInc I just did some looking around in the Railway Discord and it seems like they may actually be having issues with their templates right now; wondering if this is related somehow. _In short, the railway templating system isn't properly generating secrets, and since my template relies on those, it's breaking some stuff._ 

Is the value for `CLICKHOUSE_PASSWORD` in the Clickhouse service set to `${{secret(32)}}` by chance? 

If it is, then give this a shot: 
- go to https://generate-secret.vercel.app/32 (this generates a random secret of 32 characters) and copy the contents of the page into the `CLICKHOUSE_PASSWORD` environment variable in the Clickhouse service 
- go to https://generate-secret.vercel.app/64 and copy the contents of the page into the `SECRET_KEY_BASE` environment variable in the Plausible service
- wait until the new Clickhouse deploy is done, and edit and save your `CLICKHOUSE_DATABASE_URL` variable in the Plausible service again without changing anything 

I just spun up a new service using the template and was able to get it running by following those steps.

**Comment by KyTechInc** [comment]
@MykalMachon Ah that might be part of the issue.

Following your instructions I was able to get further, I got the DB to populate the table and did get a successful redeploy log before now being stuck looping the below error:

<img width="747" alt="image" src="https://github.com/MykalMachon/railway-plausible/assets/118579808/1c54c3a7-f323-43b9-a6cd-c9107708945a">

So far, it has not crashed though and when I hit the public railway domain I do get the register page for Plausible as expected. Just not sure if those loops errors in the build log are normal for this template?

**Comment by MykalMachon** [comment]
Hey @KyTechInc, 
those errors were/are not happening in the version of the template I spun up around a month ago when I first made it. 
That said, in the new project I just spun up, I am seeing those errors but everything seems to be working... 

If you open the URL for your plausible analytics service it should let you sign up for an account and setup your site now! 
In my testing it seems like things are working as normal with exception to those logs, but let me know if you run into any more issues. 

_I'm also going to keep this issue open until that secret generation issue sorts itself out_

**Comment by KyTechInc** [comment]
@MykalMachon Would seem something has changed since a month ago (I'm assuming on the Railway side if you haven't pushed anything to this repo since then)

Yes, I see the register page as normal. I've self-hosted this app before elsewhere so I will move forward as normal and I will let you know if I get any more errors.

Really appreciate your support on this!

**Comment by MykalMachon** [comment]
Closing as Railway has fixed the inciting issue now.
